### ISSUE TITLE
Set up UI framework based on the wireframe in Flutter

### ISSUE THREAD

**Issue by hsb1007** [eronka/culero#12]
We need to set up flutter project with the atomic UI component built.

This flutter project will need to be set up so it can be web app and mobile app

Wireframe progress

https://www.figma.com/file/p4gfqRDn3ma4zPaPAj8vH4?node-id=0:1&locale=en&type=design

**Comment by neo773** [comment]
Requested access

**Comment by Amanullah1002** [comment]
Request access for the same , pls allow to contribute on the issue .

**Comment by hsb1007** [comment]
Permission has been provided

**Comment by hsb1007** [comment]
> @hsb1007 I don't see any mobile screens in the figma wireframe section

Yes still work in progress for mobile. as long as all the components are built with mobile responsive in mind, it will be a good starting point

**Comment by hsb1007** [comment]
@neo773  @Amanullah1002  How are you guys doing? Anything you guys need from my end?

**Comment by neo773** [comment]
@hsb1007 
I have completed my assessment on the issue and want to start working on the code side now.
Could I get assigned to this as I was the first to ask, issues of this size on Algora are assigned.

**Comment by Amanullah1002** [comment]
solution from rutik looks fairly good.

**Comment by hsb1007** [comment]
FOr now I have assigned this to @neo773 as he has been looking at the issues and asking questions! 

I would love to see what Neo773 can do for now!

**Comment by Rutik7066** [comment]
> solution from rutik looks fairly good.
> 

Thank you so much @Amanullah1002

**Comment by hsb1007** [comment]
@neo773  How are we doing?

**Comment by hsb1007** [comment]
> Hi, @hsb1007 if @neo773 is not working on the I am ready to start working on it and I can complete this on priority. if you assign me , I have made an initial PR as well

Yes it has been a while without communication.. I will assign it to you! Thank you Rutik

**Comment by Rutik7066** [comment]
- Thank you so much @hsb1007  for assigning this to me. I'll start working on it.
-

**Comment by neo773** [comment]
@hsb1007 
Hi Ben,
I was working on it already didn't reply as I had to attend university today and just got online.

**Comment by neo773** [comment]
@Rutik7066 
Your initial PR was not substantial. you literally just ran flutter cli generate command I did that too

**Comment by Rutik7066** [comment]
Hi @hsb1007 could you please resolve this. I am working..

**Comment by Rutik7066** [comment]
@neo773 can't you look @hsb1007 has assigned me this issue because of you were not communicating. Not because of me

**Comment by hsb1007** [comment]
@Rutik7066  @neo773   to be honest, I am not too impressed by the progress I am seeing so far. 

 Please complete, whoever completes it in good quality quicker will be rewarded

**Comment by neo773** [comment]
@hsb1007 
Have you looked at the draft PR I've attached a demo

**Comment by hsb1007** [comment]
no movement on the ticket, i am closing this issue and will do different approach

**Comment by Rutik7066** [comment]
Hi @hsb1007 i have completed all the components you have asked do you want screenshot? please check the latest  commit on PR.
