### ISSUE TITLE
Set up the base backend API for the application

### ISSUE THREAD

**Issue by hsb1007** [eronka/culero#13]
We are looking to build rest api in Nest for this application.

As a starting point, the api needs to have the foundation in Nest and social login and registration

Facebook
Linked in
Apple
Google

Open to suggestion in terms of database and whether we need containerisation

**Comment by ibishal** [comment]
can i get assigned and work on it

**Comment by Jayanth-Parthsarathy** [comment]
Hey @hsb1007 . I have worked on multiple auth providers in nestjs before. I would love to work on this

**Comment by 35C4n0r** [comment]
@hsb1007 kindly assign it to me

**Comment by rishi-raj-jain** [comment]
All the best, @35C4n0r. Feel free to refer the article: https://dev.to/reeshee/authenticating-users-via-google-oauth-20-using-nitro-by-unjs-and-deno-land-mmb for API only authorization using Web Standards.

**Comment by 35C4n0r** [comment]
@hsb1007 is it possible to get some more info on this issue, for like the project structure, so I can get started with this.

**Comment by hsb1007** [comment]
> @hsb1007 is it possible to get some more info on this issue, for like the project structure, so I can get started with this.

This is my very first bounty I have created ever so I am still learning how to use this bounty system! 
Rajdip has started project and submit pull request with update already! so I have assigned this to him

Hope this is how it works?

**Comment by 35C4n0r** [comment]
@hsb1007 I understand, I'm also relatively new here. As for the bounty system, every org has different preferences, Some like to assign the tasks meanwhile some leave the tasks open to all and review each PR while selecting the best ones among them.

**Comment by hsb1007** [comment]
> @hsb1007 I understand, I'm also relatively new here. As for the bounty system, every org has different preferences, Some like to assign the tasks meanwhile some leave the tasks open to all and review each PR while selecting the best ones among them.


Ohh I see! Good to know! Thank you
