### ISSUE TITLE
Create sitemap.xml that includes all the user profiles & rating for SEO

### ISSUE THREAD

**Issue by anehzat** [eronka/culero#17]
[Similar to ecom product reviews](https://developers.google.com/search/blog/2014/10/best-practices-for-xml-sitemaps-rssatom)

<img width="709" alt="image" src="https://github.com/eronka/culero/assets/4149765/4c075c83-4ce6-4bee-8dca-acc7e2e3f7da">

**Comment by Bhavyajain21** [comment]
Can I be assigned?

**Comment by hsb1007** [comment]
> Can I be assigned or @hsb1007 would you like to work on it, since it's assigned to you?

Go for it mate!

**Comment by Bhavyajain21** [comment]
Thanks for assigning!

**Comment by Bhavyajain21** [comment]
Please review @anehzat / @hsb1007
