### ISSUE TITLE
Create API spec in Open API based on Figma

### ISSUE THREAD

**Issue by hsb1007** [eronka/culero#18]
Create API spec in Open API based on Figma

https://www.figma.com/file/p4gfqRDn3ma4zPaPAj8vH4/Review-People?type=design&node-id=0%3A1&mode=design&t=j9oj9FfTb2g8X8Ju-1

**Comment by mrkirthi-24** [comment]
in waitlist if @35C4n0r gives up

**Comment by 35C4n0r** [comment]
Something came up, @mrkirthi-24 passing on the issue to you.

**Comment by hsb1007** [comment]
> requested access to figma file

Approved!

**Comment by mrkirthi-24** [comment]
@hsb1007 Can you share me some resources? or please explain all parts of figma file

**Comment by hsb1007** [comment]
> @hsb1007 Can you share me some resources? or please explain all parts of figma file

Hi @mrkirthi-24  I am happy to walk you through the Figma via call if it works? 

Think of the project as professional profiles where people can leave reviews!

**Comment by hsb1007** [comment]
@mrkirthi-24 are you available for discussion? what timezone are you in?

**Comment by mrkirthi-24** [comment]
@hsb1007 I am available to discuss after 7pm IST.

**Comment by hsb1007** [comment]
Hi @mrkirthi-24  that will be 1:30am for me.  any time in the morning in your timezone or earlier  in the afternoon?

**Comment by mrkirthi-24** [comment]
I will be busy in meetings.
