### ISSUE TITLE
Create  API spec in Open API based on Figma

### ISSUE THREAD

**Issue by hsb1007** [eronka/culero#24]
Create API spec in Open API based on Figma

https://www.figma.com/file/p4gfqRDn3ma4zPaPAj8vH4/Review-People?type=design&node-id=0%3A1&mode=design&t=j9oj9FfTb2g8X8Ju-1

Quick summary of what Culero is.

This application is a professional network where people can leave reviews and ratings for other people, with an ability to remain anonymous.

It allows people to freely express their feeling about the professional relationship and performance and promote transparency.

In terms of user database, there are multiple ways of enter.

1. self registration (social)
2. logged-in-user enters other person's social profile link into Culero, which then also creates profile within Culero, for the loggedin user to leave reviews

<img width="738" alt="image" src="https://github.com/eronka/culero/assets/4149765/7ff5ae41-eb4d-46b9-ba7b-791e9c9a966f">

3. import from friends in network (via social login) into Culero as a user.

And the rest should be self explanatory in the wireframe.

should you have any question, please feel free to reach out!

**Comment by abhishek818** [comment]
@hsb1007  have requested access for figma.

**Comment by hsb1007** [comment]
@rishi-raj-jain @abhishek818 @ezhil56x  Hi all, has anyone made any progress so far?

Thanks!
