### ISSUE TITLE
Adding user registration API 

### ISSUE THREAD

**Issue by hsb1007** [eronka/culero#25]
<img width="1291" alt="image" src="https://github.com/eronka/culero/assets/4149765/4cfcddcf-6c34-4c5f-9235-f5195f0a03b1">

- Email and password will be parameters of the call
- Backend password strength validation required
- email verification process required
- login using unverified email needs to be blocked from loging in

** Added
- Another API call to add full name and professional heading
- Another API call to add profile image

<img width="687" alt="image" src="https://github.com/eronka/culero/assets/4149765/a9d3e8e4-3b44-41a6-ab03-314bb5733a6e">
<img width="693" alt="image" src="https://github.com/eronka/culero/assets/4149765/9b840a7d-fc01-40fd-90e9-427b6310fefa">

**Comment by Bhavyajain21** [comment]
Can I be assigned?

**Comment by rajdip-b** [comment]
@hsb1007 hey, for image upload, do you have any specific storage in mind?

**Comment by rajdip-b** [comment]
@Bhavyajain21 would you be attempting this one? I saw you got assigned to another issue.

**Comment by rajdip-b** [comment]
@hsb1007 mind dropping your discord channel/handle?

**Comment by hsb1007** [comment]
> @hsb1007 hey, for image upload, do you have any specific storage in mind?

Good question! AWS S3!

**Comment by rajdip-b** [comment]
> > @hsb1007 hey, for image upload, do you have any specific storage in mind?
> 
> Good question! AWS S3!

Uh, cool! Do you have any connection strings/etc I can use? Also, _the_heisenberg this is my discord ID, please drop me a text so I can discuss the features with you!

**Comment by Bhavyajain21** [comment]
@rajdip-b you can go ahead with this, I am cancelling my attempt

cc: @hsb1007

**Comment by hsb1007** [comment]
> @hsb1007 mind dropping your discord channel/handle?

https://discord.gg/tyaRVrJsDW
