### ISSUE TITLE
API to leave comments for users

### ISSUE THREAD

**Issue by hsb1007** [eronka/culero#26]
<img width="459" alt="image" src="https://github.com/eronka/culero/assets/4149765/cb1aae05-5201-4e51-97a3-ff04ceec6e53">

As an authenticated user, you can leave review for other users along with star ratings for 

- Professionalism
- Reliability
- Communication

And one thing missing from the screenshot is a boolean value to mark the review submitter as anonymous

**Comment by tarunrajput** [comment]
/attempt #26
can I get assigned?
