### ISSUE TITLE
Connecting Social login to existing users

### ISSUE THREAD

**Issue by hsb1007** [eronka/culero#28]
API for users to connect their social accounts to their existing account they registered using email

<img width="627" alt="image" src="https://github.com/eronka/culero/assets/4149765/2316928e-eaf7-435e-abe2-f8786e7ab141">

Base API for social registration already exists, please utilise it

**Comment by Bhavyajain21** [comment]
Can I be assigned? @hsb1007 

/attempt #28

**Comment by Bhavyajain21** [comment]
Thanks for assigning @hsb1007
