### ISSUE TITLE
Flutter main page and registration process

### ISSUE THREAD

**Issue by hsb1007** [eronka/culero#32]
Building main page and registration process to be built in Flutter.

[Culero-compressed.pdf](https://github.com/eronka/culero/files/14600040/Culero-compressed.pdf)

And this is the flow  (hopefully it is big enough to make sense out of it
![image](https://github.com/eronka/culero/assets/4149765/acfb2c8a-5a09-4c90-8bc4-fadef142d2de)

Or this is the figma file for reference

[https://www.figma.com/file/p4gfqRDn3ma4zPaPAj8vH4/Culero?type=design&node-id=0%3A1&mode=design&t=ueh9yMSmqEcSoa7a-1](https://www.figma.com/file/p4gfqRDn3ma4zPaPAj8vH4/Culero?type=design&node-id=0%3A1&mode=design&t=ueh9yMSmqEcSoa7a-1)

Please build it as mobile responsive

**Comment by aadarsh-nagrath** [comment]
Have requested access to figma file

**Comment by Rutik7066** [comment]
Hi @aadarsh-nagrath I have recently completed the atom part of the project now I am working on this one by the end of the day I will be submitting the final code.

**Comment by Rutik7066** [comment]
@aadarsh-nagrath you can take on this issue.

**Comment by hsb1007** [comment]
@Rutik7066  How are you going with the other one? #12  ?

**Comment by Rutik7066** [comment]
Nope, I will complete by my self @aadarsh-nagrath wanted to work on this issue.

**Comment by hsb1007** [comment]
@Sarveshk76 @aadarsh-nagrath Do you need anything else for us to complete this?

**Comment by Rutik7066** [comment]
@hsb1007 They would probably need to atom layer of project

**Comment by hsb1007** [comment]
@Rutik7066  When do you think you can complete this project?

**Comment by Rutik7066** [comment]
> @Rutik7066  When do you think you can complete this project?
> 

By the end of tomorrow I will complete both #32 and #12

**Comment by hsb1007** [comment]
> > @Rutik7066  When do you think you can complete this project?
> 
> By the end of tomorrow I will complete both #32 and #12

Looking forward to it!

**Comment by Rutik7066** [comment]
@hsb1007 if I get one pager as you mentioned in the figma it will help me alot.

**Comment by Rutik7066** [comment]
@hsb1007 and aslo need to know what icon pack we are using I have left comment on figma for this just waiting for reply.

**Comment by hsb1007** [comment]
@Rutik7066  How are we progressing!

**Comment by Rutik7066** [comment]
@hsb1007 just few components to be built.

**Comment by hsb1007** [comment]
> @hsb1007 just few components to be built.

Great ! Are we on track to finalise this (Without the icon)

**Comment by Rutik7066** [comment]
> > @hsb1007 just few components to be built.
> 
> Great ! Are we on track to finalise this (Without the icon)

I have added material icon after i didn't get any response and continued with it.

**Comment by Rutik7066** [comment]
@hsb1007 do i have to create frontend only (without api calls and logic ) to claim this issue.

**Comment by hsb1007** [comment]
> @hsb1007 do i have to create frontend only (without api calls and logic ) to claim this issue.

Yes just frontend !

**Comment by Rutik7066** [comment]
@hsb1007 apologies for the late update
I am not feeling well.  I have committed the work for atom & molecules part. I will complete and update this issue tomorrow.

**Comment by hsb1007** [comment]
> @hsb1007 apologies for the late update I am not feeling well. I have committed the work for atom & molecules part. I will complete and update this issue tomorrow.

Hope you feel better now!

**Comment by hsb1007** [comment]
@Rutik7066 are you on track to finish today?

**Comment by hsb1007** [comment]
no movement on the issue, i am closing this ticket and do another approach

**Comment by Rutik7066** [comment]
@hsb1007  2 Pages left only i am completing this issue in few hours

**Comment by Rutik7066** [comment]
Hi @hsb1007 please check https://github.com/eronka/culero-api/pull/20
