### ISSUE TITLE
API to get the latest review list along with the user profiles

### ISSUE THREAD

**Issue by hsb1007** [eronka/culero#33]
API to get the latest review list along with the user profiles of the review submissions.

1 for logged in user 
<img width="349" alt="image" src="https://github.com/eronka/culero/assets/4149765/af4904f9-b995-412b-a5c5-a57eac722662">

2 for other user's profile

<img width="301" alt="image" src="https://github.com/eronka/culero/assets/4149765/265a8a85-6ae1-4ed5-9b89-cccb288a751e">

**Comment by 35C4n0r** [comment]
@hsb1007 do we want two seperate endpoints for this like: `dashboard/reviews` <-- for first image and `reviews/reviweeUserId` <-- for second image.
