### ISSUE TITLE
Additional api for user to add profile image / name and profesisonal heading to their profiles

### ISSUE THREAD

**Issue by hsb1007** [eronka/culero#38]
2 api calls

1. Another API call to add full name and professional heading
2. Another API call to add profile image

<img width="720" alt="image" src="https://github.com/eronka/culero/assets/4149765/305e278e-c06c-46b6-b55f-fd919b19f7a9">

**Comment by Bhavyajain21** [comment]
Can I be assigned?

**Comment by hsb1007** [comment]
I will be assigning to @rajdip-b  as it is off the work he was doing !

**Comment by hsb1007** [comment]
if @rajdip-b doesn't want to take it, I can assign to you! @Bhavyajain21

**Comment by Bhavyajain21** [comment]
I see. Cool, no worries.

**Comment by rajdip-b** [comment]
Hey mate @hsb1007 I already did this in my other PR :) if you feel like you can tip me off for that!
