### ISSUE TITLE
Improve the flow

### ISSUE THREAD

**Issue by hsb1007** [eronka/culero#50]
- [ ] #51 
- [ ] #52 
- [ ] #53 
- [ ] #54

**Comment by rajdip-b** [comment]
Can you split it up into sub issues?

**Comment by Bhavyajain21** [comment]
Sure @rajdip-b , will do!

Thanks @hsb1007 for assigning!

**Comment by rajdip-b** [comment]
Hey bro @Bhavyajain21 we are creating CI/CD pipelines so will be needing #53 and #54 on priority :D hope you can deliver that!

**Comment by Bhavyajain21** [comment]
Hey @rajdip-b , Sure! On it!

**Comment by rajdip-b** [comment]
Awesome bro
