### ISSUE TITLE
CI/CD and deploy the API

### ISSUE THREAD

**Issue by hsb1007** [eronka/culero#55]
CI/CD to be set up for the rest API for Fly.io and Supabase

**Comment by rajdip-b** [comment]
Yep I'm up

**Comment by hsb1007** [comment]
Thanks for the chat =) let's get this sorted!

**Comment by ezhil56x** [comment]
/attempt #55
@hsb1007 @rajdip-b 
Can I get assigned?

**Comment by rajdip-b** [comment]
> /attempt #55 @hsb1007 @rajdip-b Can I get assigned?
> [Algora profile](https://console.algora.io/@/ezhil56x) 	Completed bounties 	Tech 	Active attempts 	Options
> @ezhil56x 	16 bounties from 10 projects 	
> JavaScript, TypeScript,
> Rust & more
> 	
> 	[Cancel attempt](https://console.algora.io/api/bounties/cltzrjr9w0006id0fky9joxgx/cancel-attempt)

hey bro, this issue has already been solved. All the confusions are because the tip command isnt working :(

**Comment by ezhil56x** [comment]
@rajdip-b Alright! `/tip` should be used in PR

**Comment by rajdip-b** [comment]
Oh! Had no idea!

**Comment by mittalyashu** [comment]
I would like to pick up this issue, can you (@hsb1007) share more context in the issue description?

**Comment by rajdip-b** [comment]
Hey bro @mittalyashu, this has already been implemented. There were some confusions while doing a tip. The bounty was created accidentally.

**Comment by mittalyashu** [comment]
I see. Okie. 🙂

**Comment by mittalyashu** [comment]
If this issue is completed, you can mark it as closed. 🙂

**Comment by rajdip-b** [comment]
> If this issue is completed, you can mark it as closed. 🙂

Unfortunately I'm not the repo maintainer😭

**Comment by hsb1007** [comment]
Thanks team I am closing it!
